on: push
jobs:
  basic_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - shell: bash
      env: 
        APIKEY: ${{ secrets.SHEET_KEY }}
      run: | 
        cd tests/dataset/ && bash report.sh ${{ secrets.SHEET_KEY }}


